In [1]:
import cv2


In [2]:
import pandas as pd

In [3]:
import numpy as np

In [26]:
input_images3=[]
target3=[]
count2=0
capture_video=cv2.VideoCapture(0)
#     time.sleep(5)
for i in range(2):
    no_of_images3=0
#         capture_video=cv2.VideoCapture(0)
#         time.sleep(5)
    input("enter to start")
    while True:
        _,image1=capture_video.read(0)
        if not _:
            break
        gray5=cv2.cvtColor(image1,cv2.COLOR_BGR2GRAY)
        haarcascade=cv2.CascadeClassifier("cascades/haarcascade_frontalface_default.xml")
        detected_objects=haarcascade.detectMultiScale(gray5,1.2,9)
#             if len(detected_objects)>1:
#                 continue
        for bbox in detected_objects:
            x,y,w,h=bbox
            cv2.rectangle(image1,(x,y),(x+w,y+h),(0,0,255),3)
            crop3=gray5[y:y+h,x:x+w]
            crop3=cv2.resize(crop3,(100,100))
            input_images3.append(crop3)
            target3.append(count2)
            no_of_images3+=1
            cv2.imshow("cropped",crop3)
            key=cv2.waitKey(1)
            cv2.imshow("image",image1)
#             if(cv2.waitKey(1) & 0xFF==ord('q')):
#                 break
#             if cv2.getWindowProperty("Generated video", 4) < 1:
#                 break
        if no_of_images3==500:
            break  
#             capture_video.release()
#             cv2.destroyAllWindows()
    count2+=1
    cv2.destroyAllWindows()
    print(input_images3)
    print(count2)
capture_video.release()
    #normalization
#     input_images=input_images/255
    #reshaping to keep every pixel value inside an array
#     input_images = input_images.reshape(1000,100,100,1)


enter to startl
[array([[ 81,  77,  69, ..., 104, 103, 104],
       [ 81,  77,  70, ..., 101, 100,  99],
       [ 80,  77,  72, ...,  97,  97,  95],
       ...,
       [ 72,  71,  72, ..., 218, 146, 124],
       [ 70,  71,  72, ..., 210, 138, 119],
       [ 69,  70,  71, ..., 201, 132, 109]], dtype=uint8), array([[ 79,  76,  68, ..., 105, 103, 103],
       [ 80,  80,  75, ...,  98,  98,  98],
       [ 82,  79,  73, ...,  94,  92,  93],
       ...,
       [ 73,  72,  71, ...,  83,  83,  80],
       [ 71,  73,  73, ...,  83,  83,  80],
       [ 73,  74,  76, ...,  85,  83,  82]], dtype=uint8), array([[ 85,  80,  73, ..., 106,  99,  99],
       [ 84,  79,  69, ..., 103,  95,  98],
       [ 83,  78,  65, ..., 108, 100,  97],
       ...,
       [ 70,  72,  74, ..., 228, 153, 126],
       [ 69,  72,  74, ..., 224, 147, 116],
       [ 69,  71,  73, ..., 211, 144, 107]], dtype=uint8), array([[104,  86,  82, ..., 108, 105, 108],
       [ 99,  85,  78, ..., 107, 106, 107],
       [101,  90,  81,

enter to starts
[array([[ 81,  77,  69, ..., 104, 103, 104],
       [ 81,  77,  70, ..., 101, 100,  99],
       [ 80,  77,  72, ...,  97,  97,  95],
       ...,
       [ 72,  71,  72, ..., 218, 146, 124],
       [ 70,  71,  72, ..., 210, 138, 119],
       [ 69,  70,  71, ..., 201, 132, 109]], dtype=uint8), array([[ 79,  76,  68, ..., 105, 103, 103],
       [ 80,  80,  75, ...,  98,  98,  98],
       [ 82,  79,  73, ...,  94,  92,  93],
       ...,
       [ 73,  72,  71, ...,  83,  83,  80],
       [ 71,  73,  73, ...,  83,  83,  80],
       [ 73,  74,  76, ...,  85,  83,  82]], dtype=uint8), array([[ 85,  80,  73, ..., 106,  99,  99],
       [ 84,  79,  69, ..., 103,  95,  98],
       [ 83,  78,  65, ..., 108, 100,  97],
       ...,
       [ 70,  72,  74, ..., 228, 153, 126],
       [ 69,  72,  74, ..., 224, 147, 116],
       [ 69,  71,  73, ..., 211, 144, 107]], dtype=uint8), array([[104,  86,  82, ..., 108, 105, 108],
       [ 99,  85,  78, ..., 107, 106, 107],
       [101,  90,  81,

In [27]:
len(input_images3)

1000

In [28]:
len(target3)

1000

In [29]:
input_images3_normalized=np.array(input_images3)/255.0
input_images3_normalized

array([[[0.31764706, 0.30196078, 0.27058824, ..., 0.40784314,
         0.40392157, 0.40784314],
        [0.31764706, 0.30196078, 0.2745098 , ..., 0.39607843,
         0.39215686, 0.38823529],
        [0.31372549, 0.30196078, 0.28235294, ..., 0.38039216,
         0.38039216, 0.37254902],
        ...,
        [0.28235294, 0.27843137, 0.28235294, ..., 0.85490196,
         0.57254902, 0.48627451],
        [0.2745098 , 0.27843137, 0.28235294, ..., 0.82352941,
         0.54117647, 0.46666667],
        [0.27058824, 0.2745098 , 0.27843137, ..., 0.78823529,
         0.51764706, 0.42745098]],

       [[0.30980392, 0.29803922, 0.26666667, ..., 0.41176471,
         0.40392157, 0.40392157],
        [0.31372549, 0.31372549, 0.29411765, ..., 0.38431373,
         0.38431373, 0.38431373],
        [0.32156863, 0.30980392, 0.28627451, ..., 0.36862745,
         0.36078431, 0.36470588],
        ...,
        [0.28627451, 0.28235294, 0.27843137, ..., 0.3254902 ,
         0.3254902 , 0.31372549],
        [0.2

In [30]:
input_images3_normalized_reshaped=input_images3_normalized.reshape(1000,100,100,1)

In [31]:
input_images3_normalized_reshaped

array([[[[0.31764706],
         [0.30196078],
         [0.27058824],
         ...,
         [0.40784314],
         [0.40392157],
         [0.40784314]],

        [[0.31764706],
         [0.30196078],
         [0.2745098 ],
         ...,
         [0.39607843],
         [0.39215686],
         [0.38823529]],

        [[0.31372549],
         [0.30196078],
         [0.28235294],
         ...,
         [0.38039216],
         [0.38039216],
         [0.37254902]],

        ...,

        [[0.28235294],
         [0.27843137],
         [0.28235294],
         ...,
         [0.85490196],
         [0.57254902],
         [0.48627451]],

        [[0.2745098 ],
         [0.27843137],
         [0.28235294],
         ...,
         [0.82352941],
         [0.54117647],
         [0.46666667]],

        [[0.27058824],
         [0.2745098 ],
         [0.27843137],
         ...,
         [0.78823529],
         [0.51764706],
         [0.42745098]]],


       [[[0.30980392],
         [0.29803922],
         [0.26

In [32]:
from keras.utils import np_utils

In [33]:
target3=np_utils.to_categorical(target3)

In [34]:
target3[:100]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(input_images3_normalized_reshaped,target3)

In [36]:
X_train.shape,X_test.shape,Y_train.shape,Y_train.shape

((750, 100, 100, 1), (250, 100, 100, 1), (750, 2), (750, 2))

In [37]:
from keras.models import Sequential
from keras.layers import Dense,Activation,Conv2D,MaxPooling2D,Dropout,Flatten
from keras.optimizers import SGD
from keras.callbacks import ModelCheckpoint

In [38]:
model=Sequential()

In [39]:
model.add(Conv2D(300, (3,3), input_shape=(100, 100, 1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(100,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Dropout(0.3))
model.add(Flatten())

model.add(Dense(50,activation='relu'))
model.add(Dense(2, activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])

In [40]:
cp=ModelCheckpoint('best_one',verbose=0,save_best_only=True)
model.fit(X_train,Y_train,epochs=5,callbacks=[cp],validation_split=0.2)

Epoch 1/5
19/19 [==============================] - ETA: 0s - loss: 0.7843 - accuracy: 0.5717WARNING:tensorflow:From C:\Users\KIIT\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: best_one\assets
19/19 [==============================] - 40s 2s/step - loss: 0.7843 - accuracy: 0.5717 - val_loss: 0.6253 - val_accuracy: 0.4933
Epoch 2/5
19/19 [==============================] - 38s 2s/step - loss: 0.4910 - accuracy: 0.7667 - val_loss: 0.4575 - val_accuracy: 1.0000
Epoch 3/5
19/19 [==============================] - 41s 2s/step - loss: 0.3934 - accuracy: 0.9233 -

In [4]:
from keras.models import load_model
model=load_model('best_one')

In [5]:
import os
import imghdr
import smtplib
from email.message import EmailMessage
capture_video=cv2.VideoCapture(0)
img_counter=0

while True:
    _,image1=capture_video.read(0)
    gray6=cv2.cvtColor(image1,cv2.COLOR_BGR2GRAY)
    haarcascade=cv2.CascadeClassifier("cascades/haarcascade_frontalface_default.xml")
    detected_objects=haarcascade.detectMultiScale(gray6,1.2,9)
    for bbox in detected_objects:
        x,y,w,h=bbox
        cv2.rectangle(image1,(x,y),(x+w,y+h),(0,0,255),3)
        crop3=gray6[y:y+h,x:x+w]
        cropped_image=cv2.resize(crop3,(100,100))
        normalized_image=cropped_image/255
        reshaped_face=np.reshape(normalized_image, (1,100,100,1))
        result=model.predict(reshaped_face)[0]
        if result[0]>0.20:
            img_counter+=1
            
            if img_counter==1:
                _,frame=capture_video.read()
                img_name = "Intruder{}.png".format(img_counter)
                cv2.imwrite(img_name, frame)
                user = os.environ.get('EMAIL')
                password = os.environ.get('PYTHONPASSWORD')
                msg=EmailMessage()
                msg['Subject']="Intruder Alert!!"
                msg['From']=user
                msg['To']=user
                msg.set_content("Intruder identified at your door, suspect's photo is attached below!")
                with open(img_name,'rb') as f:
                    file_data=f.read()
                    file_type=imghdr.what(img_name)
                    file_name=img_name
                #     print(file_type)
                msg.add_attachment(file_data,maintype='image',subtype=file_type,filename=file_name)
                with smtplib.SMTP_SSL('smtp.gmail.com',465) as smtp:
                    smtp.login(user,password)
                    smtp.send_message(msg)
            cv2.rectangle(image1,(x,y),(x+w,y+h),(0,0,255),2)
            cv2.putText(image1,"Intruder",(x,y),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)
            
#             continue
        if result[1]>0.80:
            cv2.rectangle(image1,(x,y),(x+w,y+h),(0,255,0),2)
            cv2.putText(image1,"Innocent",(x,y),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)
    cv2.imshow("image",image1)
    key=cv2.waitKey(1)
    if key==27:
        break  
cv2.destroyAllWindows()
capture_video.release()
